### ISSUE TITLE
exporting plots

### ISSUE THREAD

**Issue by kdaily** [Sage-Bionetworks/Agora#15]
allow png/pdf export of plots, csv for data, maybe a html report of all info.

**Comment by kdaily** [comment]
what's the feasibility of this?

**Comment by annagree** [comment]
Need design for how the exported item will look and what the export button will look like, etc.

**Comment by annagree** [comment]
While we are waiting for the design, let's go ahead and get started with the engineering work.

**Comment by annagree** [comment]
@stockards we will need designs for an export button as well as for how the plot should look when exported.

**Comment by stockards** [comment]
Would people like to export multiple plots at a time or would they only want to do 1 at a time?

**Comment by kdaily** [comment]
Would agree - single plots at a time are more likely. Figures need to be made to stand alone though - e.g., need to have gene name, etc from search in the figure itself.

**Comment by stockards** [comment]
<img width="717" alt="screen shot 2018-08-23 at 11 38 32 am" src="https://user-images.githubusercontent.com/38479289/44545143-1d005b00-a6c9-11e8-9c12-bdd897bb8204.png">

**Comment by annagree** [comment]
Download should be only the plot, not the entire component.

**Comment by annagree** [comment]
The font on the plots I export (using Chrome) is something like Times New Roman. Can we use a sans-serif font like whatever is used on the site?

![consistency_chg_in_exp](https://user-images.githubusercontent.com/40642407/44939209-4ad44800-ad38-11e8-9a23-2ce4dcf1c17c.png)

**Comment by Zaknarfen** [comment]
Oddly enough the code is correct. This is a bug related to the latest `Chrome` version with the library we are using to turn the `div` into a `.png` image. What happens is that with the current implementation of that library, in `Chrome`, the `div` styles for fonts are completely ignored and the browser defaults are used. Not only making text look incorrect, but some also have incorrect positions.

One alternate branch in the repository for the same library has a solution. As soon as I changed our default library version to that branch, the problem was solved (the image is bigger now though). The issue is [here](https://github.com/tsayen/dom-to-image/issues/225) and the branch is [here](https://github.com/MichalBryxi/dom-to-image). We can close this I believe.

**Comment by annagree** [comment]
@Zaknarfen I am still having issues  with image downloading. From both Chrome and Safari (on a mac) it downloads the whole component, not just the plot.

From Chrome: 
![dif_exp_tissue 1](https://user-images.githubusercontent.com/40642407/45449397-f1e6a700-b689-11e8-91e9-67e28ae17eab.png)

From Safari: 
![dif_exp_tissue-2](https://user-images.githubusercontent.com/40642407/45449405-f7dc8800-b689-11e8-9e59-df8e7344b6fa.png)

**Comment by annagree** [comment]
We would like for only the plot itself to download, like this:  
![untitled](https://user-images.githubusercontent.com/40642407/45449476-24909f80-b68a-11e8-9d0d-0d3b02682fcc.png)

**Comment by Zaknarfen** [comment]
Should be fixed, you can close if this is done @annagree.
